index.html
remove exclamation from 'hello world'
=> remove exclamation mark

index.html
I added an exclamation mark after Hello World in body tags of index.html.
=> add exclamation mark

index.html
Added unordered list with 3 list items in body index.html
=> add unordered list with 3 list items

index.html
Change font color to blue in header tag index.html
=> add font color

index.html
Changed the background color of the body to 'plum' @codeByAnnie in the index.html file. #11
=> 11-change background body color

index.html, styles/global.css
#17 @IsthisSid I added a style/global.css file, moved css from index.html to a separate global.css
=> add style/global.css and move css from index.html to separate global.css

index.html
#20 I created an images directory and added the image "hero.jpg". I added the this image to the top and center of viewport in the index.html file.
=> create images directory, add hero image to top and center of viewport

index.html, styles/global.css
#21 I updated the unordered list to my favorite projects. Each list item contains my project link and opens in a new tab. These changes were made in the index.html file. Default underline was removed and styles were applied to the links in styles/global.css (including the requested active and hover states).
=> update unordered list, link each list item to open in new tab, and apply styles to links

index.html, styles/global.css
I moved all the style elements from index.html to current css file.  Also created hero-text and added a button #28 @IsthisSid
=> [28] Add hero-text

index.html
I resolved the errors that resulted from the previous merge. @codeByAnnie
=> resolve conflicts and code error

index.html, styles/global.css
Please approve updated template @IsthisSid
=> default template

index.html, styles/global.css
@IsthisSid I updated playground to Motiv8 M3 and inspirational quotes and pictures
=> dream-achiever

about.html, index.html, styles/global.css
#33 For the landing page, I modified some of the page content: font, styles, and image positions in index.html and global.css. I moved our logo and headline to display center over the mountain top image.
#34 I added about.html file with a similar layout to the landing page. I wrote a brief description of our mission (subject to change), and will include more content later once we've agreed on a design layout.
#35 I added the navbar including an "Our Adventures" dropdown containing additional links (extra feature we probably don't need, but is there if we decide to use it).
@mdwstrat @codeTrackLift @codeByAnnie
=> [33, 34, 35] add/update navbar, format of page content, and about us section

index.html, styles/global.css
@IsthisSid  I added the authors
=> quotes-authors

index.html
#49 adjusted to 3 diff sizes for the body images. please see if you like to finalize the size for all three images @IsthisSid
=> resize-images

index.html
i adjusted the font sizes and standardized image sizes @IsthisSid
=> images fonts

pages/about.html, pages/journey.html, pages/lifestyle.html, pages/welcome.html
issue#73
linked dropdown-menu to lifestyle.html file.boilerplate added to lifestyle.html page.
=> Dropdown menu link

pages/about.html, styles/about.css
#81 Changed the navbar to mirror journey's however I kept it dark. Transparent would look messy with text overlay.  Check it out @codeByAnnie
=> change the navbar in aboutus page

index.html, pages/about.html, pages/journey.html, pages/lifestyle.html, pages/tackles.html, pages/welcome.html
=> [84] fix google tag bug

pages/tacklePost.html, pages/tackles.html, styles/tacklePost.css
#89 Changed layout on daily tackles page (main blog page) and added a blog post layout (tacklePost.html).
=> [89] Change/89 dailytackles

pages/welcome.html
=> change title to Motiv8M3 in welcome page

pages/lifestyle.html, styles/about.css
@IsthisSid Rearrange the ingredient list and steps
=> ingredients

pages/lifestyle.html, styles/about.css, styles/global.css, styles/lifestyle.css
@IsthisSid #103 created typography.css and cleaned up some unnecessary codes
=> typography

pages/welcome.html, scripts/quotes.js
#53 Added a function to randomly display quotes on the welcome page on load
=> [53] Create function to display random quotes on welcome page

pages/journey.html
Adding to 3rd journey card
- Added link to portfolio
- Added quote
=> adding to journey

pages/focusPost.html, pages/newjobPost.html, pages/tackles.html
reviewed these changes with you on discord
=> remove navbar on posts and rename post pages

pages/welcome.html, styles/global.css, styles/welcome.css
@IsthisSid #116  changed the hero layout and migrated css to welcome.css
=> changehero

pages/welcome.html, scripts/clock.js, scripts/quotes.js, styles/clock.css, styles/global.css, styles/welcome.css
@IsthisSid #118 added countdown clock to the welcome page
=> countdown-clock

pages/recipe.html, scripts/navbar.js
@IsthisSid @codeTrackLift Replaced lifestyle page
=> replace lifestyle page
